title: dhilipsiva
email: dhilipsiva@gmail.com
baseurl: ""
url: "http://dhilipsiva.com"
twitter_username: dhilipsiva
github_username:  dhilipsiva
author: dhilipsiva
twitter: dhilipsiva
paginate: 10
paginate_path: "/blog/page:num/"
markdown: kramdown
description: >
  dhilipsiva's random musings, info, interestes, experience, portfolio and
  everything.

facebook:
  admins: 1627550002

gems:
  - jekyll-feed
  - jekyll-assets
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-timeago

exclude:
  - Gemfile
  - Gemfile.lock

assets:
  autowrite: true
  cache: .asset-cache
  cache_type: filesystem
  prefix: "/assets"
  digest: true

  assets:
    - "*.jpg"

  compress:
    css: true
    js: true

  sources:
    - _assets/sass
    - _assets/images
    - _assets/javascripts

  features:
    liquid: true
    integrity: true
    automatic_img_size: true
    automatic_img_alt : true
