name: "dhilipsiva"
description: "dhilipsiva"
url: "http://dhilipsiva.com"
markdown: "redcarpet"
highlighter: 'pygments'
paginate: 10
paginate_path: "blog/page:num"

assets:
  js_compressor: uglifier
  css_compressor: sass
  sources:
    - _assets/images
    - _assets/javascripts
    - _assets/sass

sitemap:
  file: "/sitemap.xml"
  exclude:
    - "/feed.xml"
  include_posts:
    - "/index.html"
  change_frequency_name: "daily"
  priority_name: "0.80"

jekyll-press:
  exclude: 'feed.xml'
  js_options: {}
  css_options: {}
  html_options: {}

exclude:
  - "node_modules"
  - "package.json"
  - "Rakefile"
  - "Gemfile"
  - "Gemfile.lock"
  - "LICENSE"
  - "config.rb"
  - "uncss.js"
