base_url = "https://dhilipsiva.com"
compile_sass = true
build_search_index = true
theme = "terminimal"

[markdown]
highlight_code = true

_taxonomies = [
    {name = "tags"},
]

[extra]
accent_color = "green"
background_color = "dark"
logo_text = "dhilipsiva"
author = "dhilipsiva"
menu_items = [
    # {name = "home", url = "$BASE_URL"},
    # tags should only be enabled if you have "tags" taxonomy
    # see documentation below for more details
    # {name = "tags", url = "$BASE_URL/tags"},
    {name = "GitHub", url = "https://github.com/dhilipsiva", newtab = true},
    {name = "LinkedIn", url = "https://www.linkedin.com/in/dhilipsiva/", newtab = true},
    {name = "StackOverflow", url = "https://stackoverflow.com/users/1235072/dhilipsiva", newtab = true},
    {name = "Medium", url = "https://medium.com/@dhilipsiva", newtab = true},
    {name = "Email", url = "mailto:dhilipsiva@pm.me", newtab = true},
]