- name: GitHub
  url: https://github.com/dhilipsiva

- name: Twitter
  url: https://twitter.com/dhilipsiva

- name: StackOverflow
  url: http://stackoverflow.com/users/1235072/dhilipsiva

- name: AlgelList
  url: https://angel.co/dhilipsiva

- name: LinkedIn
  url: http://in.linkedin.com/in/dhilipsiva

- name: Facebook
  url: https://www.facebook.com/dhilipsiva

- name: Google+
  url: https://plus.google.com/117130129908000087872/posts

- name: Google Search
  url: https://google.com/search?q=dhilipsiva

- name: SO Careers
  url: http://careers.stackoverflow.com/dhilipsiva
