- name: "Engineering"
  description: "I am your one-stop shop for all your startup's technical needs. I can architect, implement, deploy and scale products. I build Desktop and Mobile apps too. I lack good designer skills, but that is why Bootstrap and Foundation is there for."

- name: "Technical Consulting"
  description: "I provide technical consulting on various things. I can help you choose an appropriate stack, give you ideas on how to scale your product, and a lot more. For list of things that you can consult with me, visit the <a href='/technologies'>technologies</a> page."

- name: "Tranining"
  description: "I give trainings on various stuff too. I consider myself good at it. And trust me when I say, if I was not good, I would be the first person to break the news. Again I provice traning on Agile Practices and various Programming, Git, etc. For a full list, visit the <a href='/technologies'>technologies</a> page."

- name: "Lecturing"
  description: "I have given a lot of different guest-lectures before. And almost everything is relared to Startups and technologies. Again, you can visit the <a href='/technologies'>technologies</a> page for the topics on which I usually give lectures on."
